apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: keyvalue-cdc
  annotations:
    description: 'Demo application for key-value store with change data capture'
spec:
  components:
    - name: kvcounter
      type: component
      properties:
        image: ghcr.io/wasmcloud/components/http-keyvalue-counter-rust:0.1.0
        # image: ghcr.io/wasmcloud/components/http-hello-world-rust:0.1.0
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        # - type: link
        #   properties:
        #     target: kvredis
        #     namespace: wasi
        #     package: keyvalue
        #     interfaces: [atomics, store]
        #     target_config:
        #       - name: redis-url
        #         properties:
        #           url: redis://127.0.0.1:6379
        - type: link
          properties:
            target: keyvalue-cdc
            namespace: wasi
            package: keyvalue
            interfaces: [atomics, store]
            target_config:
              - name: redis-url
                properties:
                  url: redis://127.0.0.1:6379

    - name: keyvalue-cdc
      type: component
      properties:
        image: file://./component-keyvalue-cdc/build/component_keyvalue_cdc_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target: kvredis
            namespace: wasi
            package: keyvalue
            interfaces: [atomics, store]
            target_config:
              - name: redis-url
                properties:
                  url: redis://127.0.0.1:6379

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.22.0
      traits:
        - type: link
          properties:
            target: kvcounter
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8080

    - name: kvredis
      type: capability
      properties:
        image: ghcr.io/wasmcloud/keyvalue-redis:0.25.0